name: Echo Github environment variables

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo environment variables
        shell: bash
        run: |
          echo "GITHUB_RUN_ID $GITHUB_RUN_ID"
          echo "GITHUB_EVENT_NAME $GITHUB_EVENT_NAME"
          echo "GITHUB_SHA $GITHUB_SHA"
          echo "GITHUB_REF $GITHUB_REF"
          echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF $GITHUB_BASE_REF"
          echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"
